index = "echo 'running by default; see run.toml for more'; target/debug/run build"

[build]
index = "target/debug/run build debug"
debug = "cargo build"
release = "cargo build --release"

# this is an example run.toml file.
# i wouldn't use run with single-crate projects, cargo is sufficient
